# Things-Kit Configuration Example
# Copy this file to config.yaml and adjust values as needed

# Logging configuration
logging:
  level: info        # Options: debug, info, warn, error
  encoding: json     # Options: json, console
  output_path: stdout

# gRPC server configuration
grpc:
  port: 50051

# HTTP server configuration
http:
  port: 8080
  mode: release      # Options: debug, release, test

# Database configuration
db:
  dsn: "postgres://user:password@localhost:5432/dbname?sslmode=disable"

# Redis configuration
redis:
  url: "redis://localhost:6379/0"

# Kafka consumer configuration
kafka:
  brokers: 
    - "localhost:9092"
  topic: "events"
  group_id: "things-kit-consumer"
  max_wait: "5s"
  min_bytes: 1
  max_bytes: 10485760  # 10MB
